name: device_frame
description: Mockups for common devices.
version: 0.1.2
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  xml:
  flutter_svg:
  path_drawing:
  freezed_annotation: ^0.11.0 
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.1
  freezed: ^0.11.6
  pedantic: ^1.9.0

flutter:
  assets:
    - assets/
