name: device_frame
description: Mockups for common devices.
version: 0.5.0
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_svg: ^0.23.0
  path_drawing: ^0.5.1
  freezed_annotation: ^0.15.0 
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  freezed: ^0.15.0
  flutter_lints: ^1.0.4
  xml: ^5.3.1