name: device_preview_example
description: A simple demonstration of device_preview.

version: 1.0.1

environment:
  sdk: ">=2.2.2 <3.0.0" 

dependencies:
  flutter_platform_widgets:
  device_preview:
    path: ../
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_localizations:
    sdk: flutter
  path_provider_macos:

  # This is a temporary hack to enable Windows to work. It is not recommended
  # since this package may change at any time in ways that break. 
  path_provider_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding/
      path: plugins/flutter_plugins/path_provider_fde  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true