name: device_preview
version: 0.1.2-beta
author: Aloïs Deniel <alois.deniel@outlook.com>
description: Preview of your Flutter app on various device screen configurations from one of your devices.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  flutter: 
    sdk: flutter 
 
dev_dependencies: 
  flutter_test:
    sdk: flutter