name: device_preview
version: 0.5.0-prerelease
description: Approximate how your app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.7.0 <3.0.0' 

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_frame: ^0.3.0-prerelease2
  font_awesome_flutter: ^8.8.1
  http: ^0.12.2 
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.0 
  meta: ^1.1.8 
  shared_preferences: ^0.5.11
  shared_preferences_macos: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter 
  build_runner: ^1.10.2
  freezed: ^0.12.1
  json_serializable: ^3.5.0
  pedantic: ^1.9.0
  analyzer: ^0.39.17
