name: device_preview
version: 0.7.5
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.12.0 <3.0.0' 

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  path_provider: ^2.0.1
  device_frame: ^0.5.0
  path_drawing: ^0.5.1
  http: ^0.13.0 
  freezed_annotation: ^0.15.0 
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.8
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^1.0.4
  build_runner: ^2.1.4
  freezed: ^0.15.0 
  json_serializable: ^6.0.1
  analyzer: ^2.7.0
