name: device_preview
version: 0.2.1
author: Aloïs Deniel <alois.deniel@outlook.com>
description: Preview of your Flutter app on various device screen configurations from one of your devices.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.6
  http: ^0.12.0
  flutter: 
    sdk: flutter 
  path_provider: ^1.3.1
  path_provider_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding/
      ref: 9e5ee41da03e2a6224614c2bc38b3c6dbc3bab3c
      path: plugins/flutter_plugins/path_provider_fde
 
dev_dependencies:
  flutter_test:
    sdk: flutter