name: device_preview
version: 0.2.4
author: Aloïs Deniel <alois.deniel@outlook.com>
description: Preview of your Flutter app on various device screen configurations from one of your devices.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.6
  http: ^0.12.0
  flutter: 
    sdk: flutter 
  path_provider: ^1.3.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter 