name: device_preview
version: 0.2.6+1
description: Approximate how your app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.6
  http: ^0.12.0
  path_provider: ^1.3.1
  flutter_svg: ^0.14.3
  flutter: 
    sdk: flutter 
 
dev_dependencies:
  flutter_test:
    sdk: flutter 