name: tools
description: A project for inspecting device characteristics.

version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  device_info:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter 
  pedantic: 1.8.0+1

dependency_overrides:
  pedantic: ^1.9.0


flutter:
  uses-material-design: true